# Generated by Django 3.2.5 on 2021-09-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='t',
            field=models.ManyToManyField(related_name='groups', through='groups.Membership', to='groups.Group'),
        ),
    ]
