# Generated by Django 3.2.5 on 2021-09-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_Name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_Name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
