# Generated by Django 3.2.5 on 2021-09-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210902_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
