# Generated by Django 3.2.5 on 2021-09-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='t',
            new_name='groups',
        ),
    ]
