# Generated by Django 3.2.5 on 2021-09-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
