# Generated by Django 3.2.5 on 2021-09-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='t',
            new_name='members',
        ),
    ]
