# Generated by Django 3.2.5 on 2021-09-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210902_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='posts',
        ),
    ]
